#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     r_flatheme
# | |       |  ___  |
# | |       | |   | |    Set GTK Theme for Flatpak on KDE Plasma
# | |_____  | |___| |    Based on https://forum.manjaro.org/t/how-to-consistent-flatpak-theming-in-kde-plasma/7259
# |_______| |_______|
# 
#

############################################################
# Help                                                     #
############################################################
Help() {
  cat << EOF
Usage: $(basename $0) [OPTIONS]

Set the GTK Theme for Flatpak on KDE Plasma.

OPTIONS:
  -h     Display this help message
  -s     Set the GTK theme for Flatpak.
  -u     Unset the GTK theme for Flatpak.
EOF
  exit 1
}


############################################################
# SetGTK                                                   #
############################################################
SetGTK()
{
   # Set GTK Theme
   for dir in $HOME/.var/app/*/
   do
      for i in $(seq 3 4);
      do
         confdir="${dir}config/gtk-${i}.0"
         mkdir -p $confdir
         cp $HOME/.config/gtk-$i.0/settings.ini $confdir/settings.ini
      done
   done
   echo -e "\nsetting gtk theme... done!\n"
}

############################################################
# UnsetGTK                                                 #
############################################################
UnsetGTK()
{
   # Unset GTK Theme
   for dir in $HOME/.var/app/*/
   do
      for i in $(seq 3 4);
      do
         confdir="${dir}config/gtk-${i}.0"
         rm -rf $confdir/settings.ini
      done
   done
   echo -e "\nunsetting gtk theme... done!\n"
}

############################################################
# InvalidOption                                            #
############################################################
InvalidOption()
{
   # Display Invalid Option Text
   echo -e "$(basename $0): invalid option.\n"
   Help
}

############################################################
# Main Program                                             #
############################################################

# No option supplied
if [ $# -eq 0 ]
    then
        Help
        exit;
fi

############################################################
# Process the input options. Add options as needed.        #
############################################################
# Get the options
while getopts ":hsu" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      s) # set GTK Theme
         SetGTK
         exit;;
      u) # unset GTK Theme
         UnsetGTK
         exit;;
      \?) # Invalid option
         InvalidOption
         exit;;
   esac
done