#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     r_git_clean
# | |       |  ___  |
# | |       | |   | |    Clean local repository
# | |_____  | |___| |    Download files
# |_______| |_______|
# 
#

git stash --include-untracked
git reset --hard
git clean -fd
git pull
