#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     r_importsql
# | |       |  ___  |
# | |       | |   | |    Import DATABASE.SQL.GZ
# | |_____  | |___| |    into DATABASE
# |_______| |_______|    Tested on Kubuntu 20.04 LTS
# 
#

if [ $# -eq 0 ]
    then
        echo "No arguments supplied"
    else
    
        FILEDB=$1
        if [ ! -f $FILEDB ];
        then
            echo "The file doesn't exist";
            exit;
        fi
        
        MYSQL_USER=$2
        if [ -z $MYSQL_USER ];
        then
            read -p "Enter Username: " MYSQL_USER
            if [ -z $MYSQL_USER ]; then echo "Need to enter username"; exit; fi
        fi
        
        DBNAME="${FILEDB%.*}"
        zcat $FILEDB | mysql -u $MYSQL_USER -p "${DBNAME%.*}"
        
fi
