#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     r_lamp
# | |       |  ___  |
# | |       | |   | |    LAMP Server Control
# | |_____  | |___| |    for my Testing Web server
# |_______| |_______|    running Manjaro
#
#
#

if [ $# -eq 0 ]
    then
        echo "No distro supplied. Available: debian,ubuntu,arch"
        exit;
    else
        case $1 in
            arch|Arch|ARCH|manjaro|Manjaro|MANJARO)
            DISTRO="arch"
            APACHECMD='httpd'
            MYSQLCMD='mysqld'
            SERVERGROUP='http'
            SERVERUSER='http'
            SERVERDIR='/srv/http/'
            ;;
            debian|DEBIAN|Debian|ubuntu|UBUNTU|Ubuntu)
            DISTRO="debian"
            APACHECMD='apache2'
            MYSQLCMD='mysql'
            SERVERGROUP='www-data'
            SERVERUSER='www-data'
            SERVERDIR='/var/www/html/'
            ;;
            # NOT IMPLEMENTED
            *)
            echo "Distro \"$1\" not supported"
            exit;
            ;;
        esac
fi

echo "**************************************"
echo "*                                    *"
echo "*        LAMP Server Control         *"
echo "*                                    *"
echo "**************************************"
echo ""
echo "Available commands:"
echo ""
echo "  [1] Start"
echo "  [2] Kill"
echo "  [3] Restart"
echo "  [4] Public HTML folder (Set permissions ~/public_html)"
echo "  [5] Server Root Directory (Set permissions)"
echo "  [6] Current folder at . (Set permissions . )"
echo "  [Q]uit"
echo ""
echo -n "Command [1,2,3,4,5,6,Q]:"

read input

echo ""

case "$input" in
    1)
    echo "Starting..."
    sudo systemctl start "$APACHECMD"
    sudo systemctl start "$MYSQLCMD"
    echo "LAMP Server is ON"
    ;;

    2)
    echo "Stopping..."
    sudo systemctl stop "$APACHECMD"
    sudo systemctl stop "$MYSQLCMD"
    echo "LAMP Server is OFF"
    ;;
    
    3)
    echo "Re-Starting..."
    sudo systemctl restart "$APACHECMD"
    sudo systemctl restart "$MYSQLCMD"
    echo "LAMP Server is ON"
    ;;
    
    4)
    echo "Setting permissions on ~/public_html folder ..."
    sudo chown -R "$SERVERUSER":"$SERVERGROUP" ~/public_html/
    sudo chmod -R g+rwX ~/public_html/
    echo "Done!"
    ;;

    5)
    echo "Setting permissions on Default Server Directory folder ..."
    sudo chown -R "$SERVERUSER":"$SERVERGROUP" "$SERVERDIR"
    sudo chmod -R g+rwX "$SERVERDIR"
    echo "Done!"
    ;;

    6)
    echo "Setting permissions on current folder ..."
    sudo chown -R "$SERVERUSER":"$SERVERGROUP" .
    sudo chmod -R g+rwX .
    echo "Done!"
    ;;

    quit|QUIT|Q|q|exit|EXIT|x|X) 
    echo "Bye!!!!"
    ;;
    
    # NOT IMPLEMENTED
    *)
    echo "Choose an available command!!!"
    ;;

esac

echo ""
