#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     r_lamp
# | |       |  ___  |
# | |       | |   | |    LAMP Server Control
# | |_____  | |___| |    for my Testing Web server
# |_______| |_______|
#
#
#

echo "**************************************"
echo "*                                    *"
echo "*        LAMP Server Control         *"
echo "*                                    *"
echo "**************************************"
echo "Available commands:"
echo ""
echo "  [S]tart"
echo "  [K]ill"
echo "  [R]estart"
echo "  [P]ublic HTML folder (Set permissions ~/public_html)"
echo "  [H]ttp folder at /srv (Set permissions /srv/http/)"
echo "  [Q]uit"
echo ""
echo -n "Command [S,K,R,P,V,Q]:"

read input

echo ""

case "$input" in
    start|START|S|s)
    echo "Starting..."
    sudo systemctl start httpd
    sudo systemctl start mysqld
    echo "LAMP Server is ON"
    ;;

    stop|STOP|K|k)
    echo "Stopping..."
    sudo systemctl stop httpd
    sudo systemctl stop mysqld
    echo "LAMP Server is OFF"
    ;;
    
    restart|RESTART|R|r)
    echo "Re-Starting..."
    sudo systemctl restart httpd
    sudo systemctl restart mysqld
    echo "LAMP Server is ON"
    ;;
    
    v|V|var|VAR|w|W|www|WWW)
    echo "Setting permissions on /srv/http/ folder ..."
    sudo chown -R http:http /srv/http/
    sudo chmod -R g+rwX /srv/http/
    echo "Done!"
    ;;

    p|P|public|PUBLIC)
    echo "Setting permissions on ~/public_html folder ..."
    sudo chown -R http:http ~/public_html/
    sudo chmod -R g+rwX ~/public_html/
    echo "Done!"
    ;;
   
    quit|QUIT|Q|q|exit|EXIT|x|X) 
    echo "Bye!!!!"
    ;;
    
    # NOT IMPLEMENTED
    *)
    echo "Choose an available command!!!"
    ;;

esac

echo ""
