#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     r_pdfmultiple
# | |       |  ___  |
# | |       | |   | |    Join multiple PDF from PNG from current folder
# | |_____  | |___| |    and save it into parent folder with current folder name
# |_______| |_______|
#
# Requirementes:
# -> mogrify
# -> qpdf

command -v mogrify >/dev/null 2>&1 || { echo >&2 "I require mogrify but it's not installed. Aborting."; exit 1; }
command -v qpdf >/dev/null 2>&1 || { echo >&2 "I require mogrify but it's not installed. Aborting."; exit 1; }

FILENAME=${PWD##*/}
mogrify -format jpg -quality 90 *.png
mogrify -format pdf -quality 90 *.jpg
qpdf --empty --pages *.pdf -- output.pdf
mv output.pdf ../"$FILENAME.pdf"
rm *.jpg
rm *.pdf
