#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     r_svgcleaner
# | |       |  ___  |
# | |       | |   | |    Clean and Tidy SVG
# | |_____  | |___| |    Usually used when contributing to keeferrourke/la-capitaine-icon-theme
# |_______| |_______|
#
# Requirementes:
# ->  svgcelaner [ https://github.com/RazrFalcon/svgcleaner ]
# ->  tidy [ http://www.html-tidy.org/developer ]
# ->  inkscape - Optional for exporting PNG file

command -v svgcleaner >/dev/null 2>&1 || { echo >&2 "I require svgcleaner but it's not installed. Aborting."; exit 1; }
command -v tidy >/dev/null 2>&1 || { echo >&2 "I require tidy but it's not installed. Aborting."; exit 1; }
command -v inkscape >/dev/null 2>&1 || { echo >&2 "I require inkscape but it's not installed. Aborting."; exit 1; }

shopt -s nocaseglob # Sets nocaseglob


function process_icon (){
    ICON=$1
    #echo "process the icon ${ICON}"
    svgcleaner "$ICON" "$ICON"
    tidy -q -xml -indent -wrap 0 -m "$ICON"
    inkscape --export-filename "${ICON%.*}.png" --export-area-page "$ICON"
}


if [ $# -eq 0 ]
    then
        echo "No arguments supplied"
    else
        file=$1
        case $file in
            # ALL FILES IN FOLDER
            .)
            #
            for icon in *.svg
            do
                process_icon $icon
            done
            exit;
            ;;
            # DEFAULT -  ONE SPECIFIC FILE
            *)
            # Cheking if file exists and is a valid file
            if [ -f $file ] && [ "${file: -4}" == ".svg" ]; then
                # File is exist and is allowed
                process_icon $file
            else
                echo "File \"${file}\" doesn't exist or is not a valid SVG file!"
            fi
            exit;
            ;;
        esac

fi



