#!/bin/bash
#  _______   _______
# |  _____| |  ___  |
# | |       | |   | |    Rolando Ramos Torres (@rolodoom)
# | |       | |___| |    http://rolandoramostorres.com
# |_|       |_______|
#  _         _______     
# | |       |  ___  |
# | |       | |   | |    r_svgcleaner
# | |_____  | |___| |    SVG batch processing script with svgcleaner, tidy, and inkscape
# |_______| |_______|
#

# Check if required commands are available
command -v svgcleaner >/dev/null 2>&1 || { echo >&2 "I require svgcleaner but it's not installed. Aborting."; exit 1; }
command -v tidy >/dev/null 2>&1 || { echo >&2 "I require tidy but it's not installed. Aborting."; exit 1; }
command -v inkscape >/dev/null 2>&1 || { echo >&2 "I require inkscape but it's not installed. Aborting."; exit 1; }

# Define a function to display help information
function display_help {
    echo "Usage: $(basename "$0") [FILE]"
    echo "  -h              Display this help message"
    echo "  FILE            SVG file to process, or '.' to process all SVG files in the current directory"
}


# Define a function to process an SVG icon
function process_icon (){
    ICON=$1
    #echo "process the icon ${ICON}"
    svgcleaner "$ICON" "$ICON"
    tidy -q -xml -indent -wrap 0 -m "$ICON"
    inkscape --export-filename "${ICON%.*}.png" --export-area-page "$ICON"
}

# Use getopts to handle the '-h' flag
while getopts "h" option; do
    case $option in
        h)
            display_help
            exit
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            display_help
            exit 1
            ;;
    esac
done

# Remove the processed arguments
shift $((OPTIND-1))


# Set nocaseglob to make file matching case-insensitive
shopt -s nocaseglob # Sets nocaseglob


# Check if the script is called without arguments
if [ $# -eq 0 ]
then
    echo "No arguments supplied"
    display_help
    exit 1
else
    file=$1
    case $file in
        # Process all SVG files in the current directory
        .)
            for icon in *.svg
            do
                process_icon $icon
            done
            exit;
            ;;
        # Process one specific SVG file
        *)
            # Check if the file exists and is a valid SVG file
            if [ -f $file ] && [ "${file: -4}" == ".svg" ]; then
                # Process the SVG file
                process_icon $file
            else
                echo "File \"${file}\" doesn't exist or is not a valid SVG file!"
                display_help
                exit 1
            fi
            exit;
            ;;
    esac
fi
